# Generated by Django 4.0.3 on 2022-04-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasksession_final_lenght_tasksession_init_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='create_date',
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasksession',
            name='init_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
